export const SHORT = {
    BODY: 'body',
    INTER: 'interpreter',
    SRC_TYPE: 'sourceType',
    TYPE: 'type',
    KIND: 'kind',
    LOC: 'loc',
    START: 'start',
    END: 'end',
    LINE: 'line',
    COLUMN: 'column',
    DRCTVS: 'directives',
    DECLS: 'declarations',
    PROGRAM: 'program',
    T_AWAIT: 'topLevelAwait',
    EXTRA: 'extra',
    ERRORS: 'errors',
    COMMENTS: 'comments',
    FILENAME: 'filename',
    P_PTR: '__putout_printer',
    ID_NAME: 'identifierName',
    ID: 'id',
    INDEX: 'index',
    INIT: 'init',
    VALUE: 'value',
    RAW: 'raw',
    GEN: 'generator',
};
